FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip install discord.py gTTS vosk sounddevice

COPY . /app

CMD ["python", "/app/votre_script.py"]
